---
kind: Service
apiVersion: v1
metadata:
  name: videostreamingservice
spec:
  selector:
    app: video-streaming
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 3000
      # Port accessible outside cluster
      nodePort: 30001
  type: LoadBalancer
 
 
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  selector:
    matchLabels:
      app: video-streaming
  replicas: 4
  template:
    metadata:
      labels:
        app: video-streaming
    spec:
      containers:
        - name: video-streaming
          image: video-streaming:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 3000